title: Dirty Laundry
subtitle: Without all the heartache
description: A blog about the state of web technologies and other musings about life. Inspired by a pile of dirty laundry.

email: calebmeredith8@gmail.com

permalink: pretty

home: /
baseurl:
url: http://calebmer.github.io
development: false

exclude:
  - node_modules
  - package.json
  - Makefile

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author:
        name: Caleb Meredith

markdown: kramdown
