development: false

title: "calebmer"
subtitle: ""
description: A blog about the state of web technologies and other musings about life.

email: calebmeredith8@gmail.com

permalink: pretty

home: /
baseurl:
url: https://calebmer.github.io

exclude:
  - node_modules
  - package.json
  - Makefile

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author:
        name: Caleb Meredith

markdown: kramdown
