title: Dirty Laundry
subtitle: without all the heartache

email: calebmeredith8@gmail.com

description: >
  TODO: Awesome description here

permalink: pretty

home: /
baseurl:
url: http://yourdomain.com

exclude:
  - node_modules
  - package.json
  - Makefile

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Caleb Meredith

markdown: kramdown
