# Site settings
title: Code → Software
email: calebmeredith8@gmail.com
description: Caleb Meredith’s blog.
url: https://calebmer.com
twitter_username: calebmer
github_username: calebmer
google_analytics: UA-63972614-2
header_pages:
  - about.md

# Content settings
collections:
  drafts:
    output: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode
